image: python:3.5

services:
   - postgres

before_script:
    - pip install -r requirements.txt
    - cd juanwolf_fr
    - export DJANGO_SETTINGS_MODULE='juanwolf_fr.settings_dev'

stages:
    - test

job1:
    stage: test
    script:
        - python manage.py test
    tags:
        - docker

