image: python:3.5

services:
   - postgres

before_script:
    - pip install -r requirements.txt
    - cd juanwolf_fr

stages:
    - test

job1:
    stage: test
    script:
        - python manage.py tests
    tags:
        - docker

