language: python
python:
 - "3.5"
services:
 - postgresql
env:
 - DATABASE_URL=postgres://postgres:@postgres:5432/python-test-app
install: "pip install -r requirements.txt"
script: python juanwolfs_blog/manage.py test
