version: '2'
services:
    db:
        image: postgres
        volumes: 
            - /var/lib/postgres/data:/var/lib/postgres/data
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
    django:
        build: .
        ports:
            - "8000:8000"
        links:
            - db
        

