version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ~/docker/volumes/postgresql:/var/lib/postgresql/data
  django:
    build:
      context: ../
      dockerfile: docker/Dockerfile-dev
    ports:
      - "8000:8000"
    links:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_HOST=db
      - DEBUG=True
      - PYTHONUNBUFFERED=1
    volumes:
      - ../:/opt/juanwolf_fr




